### ISSUE TITLE
Updated documentation regarding restore purchases [suggestion]

### ISSUE THREAD

**Issue by racsol** [russell-archer/StoreHelper#11]
First off, thanks for this amazing project.
I'm using this project already in one app that is live at the App Store and the first build was rejected by the reviewer because I didn't had a restore purchases button. I didn't put that button because I read in the documentation that with StoreKit 2 it's not required to have that button. 
Maybe you should updated the project document regarding that topic, because without a restore purchases button apps are being rejected. Also read on twitter about other people with apps rejected because of the same reason.

To restore I'm just using:
`StoreKit.sync()`

don't know if there's something more appropriate...

Thanks again for your work in the project!

**Comment by russell-archer** [comment]
Thanks so much for the kind comments - glad it's useful for you!

Re the Restore button: from my reading of the latest (Xcode 14/iOS16) StoreKit 2 documentation I understood that you wouldn't normally need to manually restore purchases, because StoreKit 2 does it for you automatically. However, the documentation recommends that you DO include a Restore button so that users can manually restore previous purchases/subscriptions if they're not automatically restored. So, I do always include a Restore button in my apps (which just calls AppStore.sync()). In fact, I've seen instances myself (with iOS16) where previous purchases are NOT automatically restored and users have to tap Restore.

I thought I'd got something about this in the documentation. However, I couldn't see it so I've added a section named Restoring Previous Purchases. Thanks for the excellent suggestion!

By the way, Apple states that you should only do a restore as the result of a specific user action (like tapping a Restore button). The reason is that forcing a restore causes the user to authenticate with the app store.
