### ISSUE TITLE
Any support of Privacy Manifest?

### ISSUE THREAD

**Issue by iharkatkavets** [russell-archer/StoreHelper#69]
Privacy Updates for AppStore submission

## Expected Behavior
Developers are responsible for all code included in their apps. At WWDC23, Apple introduced new privacy manifests and signatures for commonly used third-party SDKs and announced that developers will need to declare approved reasons for using a set of APIs in their app’s privacy manifest.

## Current Behavior
The library doesn't provide Privacy Manifest file

## Possible Solution
The library should provide Privacy Manifest if it collects information or access "Required Reasons API"

## Additional Info
<img width="826" alt="Screenshot 2024-03-08 at 09 26 02" src="https://github.com/russell-archer/StoreHelper/assets/1083951/807d5111-e76d-4c3a-a9c8-63218af6eead">

**Comment by russell-archer** [comment]
I’ll try and sort that out today as a matter of urgency!Interesting that it’s the first time I’ve encountered this. I successfully submitted an update to an app that uses StoreHelper with no problem. On 8 Mar 2024, at 09:09, Ihar Katkavets ***@***.***> wrote:﻿
Privacy Updates for AppStore submission
Expected Behavior
Developers are responsible for all code included in their apps. At WWDC23, Apple introduced new privacy manifests and signatures for commonly used third-party SDKs and announced that developers will need to declare approved reasons for using a set of APIs in their app’s privacy manifest.
Current Behavior
The library doesn't provide Privacy Manifest file
Possible Solution
The library should provide Privacy Manifest if it collects information or access "Required Reasons API"
Additional Info
Screenshot.2024-03-08.at.09.26.02.png (view on web)

**Comment by russell-archer** [comment]
And just to confirm, StoreHelper doesn't collect any data whatsoever 😁

**Comment by russell-archer** [comment]
Done. I've added a privacy manifest (see StoreHelper/Sources/Resources) and made sure it's correctly bundled with the target (see the package manifest). 

The privacy manifest correctly states that there's no tracking or data collection and that StoreHelper does use the UserDefaults API. All *seems* correct.

To test, if I archive an app using StoreHelper app then right-click on the archive in the archive organizer and select Generate Privacy Report I should get a report as a pdf:

![priv-manifest](https://github.com/russell-archer/StoreHelper/assets/6470403/eac26118-0c23-405d-a743-5f682a1fc779)

However, the report is always empty (no content), no matter what's in the manifest. I'm not sure if this is an Xcode bug or something I'm doing wrong. 

So, I'll leave this issue open for now. Let me know if what I've done gets you through app store review!

**Comment by Volodymyr-13** [comment]
But it should be empty, since yep - StoreHelper is not using any of these and doesn't collect any data.
Also, deadline for this is 1 May, so lib developers have a plenty of time from now to add this.

**Comment by russell-archer** [comment]
Actually that's what I thought too. However, after digging a bit deeper it turns out that I need to declare use of the UserDefaults API (StoreHelper persists a list of purchases as a fallback in case the App Store's not available).
