### ISSUE TITLE
No auto renew message above the purchase button

### ISSUE THREAD

**Issue by scottiesan** [russell-archer/StoreHelper#82]
How do you set the auto-new until cancel message?

Demo View
<img width="375" alt="Screenshot 2024-09-18 at 10 36 01 PM" src="https://github.com/user-attachments/assets/b4278d64-3007-4201-ad60-aea9f7a8f0fd">

My Test View
How come my test is not showing the auto renew message?  How do you configure this?  
<img width="371" alt="Screenshot 2024-09-18 at 10 41 27 PM" src="https://github.com/user-attachments/assets/41c9e6d0-6735-4456-bc1d-86219e9260b8">

**Comment by russell-archer** [comment]
It looks to me like both these screenshots are from the StoreKit `SubscriptionStoreView`. If so, that message about "Plan auto-renews ..." is generated **by the StoreKit `SubscriptionStoreView`, not by `StoreHelper`**. There's no way to configure this that I know of.

![shot1](https://github.com/user-attachments/assets/e069c9e8-0350-4af4-b056-6593f69783e1)

I added use of the StoreKit `SubscriptionStoreView` to show how `StoreHelper` can work with the newer StoreKit Views that have been introduced, so it's not strictly part of `StoreHelper`.

But it's weird that you're not seeing the auto-renew message. A few things to check: are your subscriptions auto-renewable (rather than the older non-renewing)? Also, did you cancel the subscription?

**Comment by scottiesan** [comment]
@russell-archer Thank you for pointing me in the right direction!  I think there is an issue receiving data from app store connect regarding my subscription.  
https://forums.developer.apple.com/forums/thread/759122

**Comment by russell-archer** [comment]
That's interesting... So `SubscriptionStoreView(productIDs: ["myid1", "myid2"])` works OK, but `SubscriptionStoreView(groupID: "someGroupId")` doesn't!

I'll keep an eye this and leave the issue open for now. Thanks for the link to the issue on the dev forums!

**Comment by scottiesan** [comment]
Once I submit to the Appstore and got rejected, I can't seem to pull the subscription info from Xcode project.

**Comment by scottiesan** [comment]
Once I submit to the Appstore and got rejected, I can't seem to pull the subscription info from Xcode project.

**Comment by russell-archer** [comment]
You mean requesting localised `Product` information from the App Store doesn't work? What about if you use sandbox testing?

**Comment by scottiesan** [comment]
When you add a storekit config file from xcode, it would ask if you want to pull data from app store.  After putting in the app info and finish.  It should pull the app store subscription info.   This was working fine until  I submit app for review.  I wonder if because all my subscription are now in 'waiting for review'

**Comment by russell-archer** [comment]
Ah, I understand now. I'm afraid that's not something I've ever encountered before. I think you'll need to contact the App Store support team if it doesn't start working after it gets through the review process.
